
openapi: 3.0.0
info:
  title: Streaming Video Service API
  version: "1.0.0"
  description: API for managing movies and reviews in a streaming video service with authentication.

servers:
  - url: http://localhost:8000/api/v1

# ✅ Вынес security на глобальный уровень
security:
  - ApiKeyAuth: []

paths:
  /movies:
    get:
      summary: Retrieve a list of all available movies
      operationId: getAllMovies
      security:
        - ApiKeyAuth: []
      responses:
        '200':
          description: List of movies
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Movie'
        '401':
          description: Unauthorized - Invalid API Key
        '500':
          description: Internal Server Error
    post:
      summary: Add a new movie to the catalog
      operationId: createMovie
      security:
        - ApiKeyAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Movie'
      responses:
        '201':
          description: Movie created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Movie'
        '400':
          description: Bad Request - Invalid Data Provided
        '401':
          description: Unauthorized - Invalid API Key
        '500':
          description: Internal Server Error

  /movies/{movieId}:
    get:
      summary: Retrieve details of a specific movie
      operationId: getMovieById
      security:
        - ApiKeyAuth: []
      parameters:
        - in: path
          name: movieId
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Detailed information about the movie
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Movie'
        '404':
          description: Movie not found
        '401':
          description: Unauthorized - Invalid API Key
        '500':
          description: Internal Server Error
    put:
      summary: Update information of an existing movie
      operationId: updateMovie
      security:
        - ApiKeyAuth: []
      parameters:
        - in: path
          name: movieId
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Movie'
      responses:
        '200':
          description: Movie updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Movie'
        '400':
          description: Bad Request - Invalid Data Provided
        '404':
          description: Movie not found
        '401':
          description: Unauthorized - Invalid API Key
        '500':
          description: Internal Server Error
    delete:
      summary: Remove an existing movie
      operationId: deleteMovie
      security:
        - ApiKeyAuth: []
      parameters:
        - in: path
          name: movieId
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Movie deleted successfully
        '404':
          description: Movie not found
        '401':
          description: Unauthorized - Invalid API Key
        '500':
          description: Internal Server Error

  /reviews:
    get:
      summary: Retrieve all reviews for movies
      operationId: getAllReviews
      security:
        - ApiKeyAuth: []
      parameters:
        - in: query
          name: movieId
          schema:
            type: integer
          description: Filter reviews by movie ID
      responses:
        '200':
          description: List of reviews
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Review'
        '401':
          description: Unauthorized - Invalid API Key
        '500':
          description: Internal Server Error
    post:
      summary: Add a new review for a movie
      operationId: createReview
      security:
        - ApiKeyAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Review'
      responses:
        '201':
          description: Review created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Review'
        '400':
          description: Bad Request - Invalid Data Provided
        '401':
          description: Unauthorized - Invalid API Key
        '500':
          description: Internal Server Error

  /reviews/{reviewId}:
    get:
      summary: Retrieve a specific review by ID
      operationId: getReviewById
      security:
        - ApiKeyAuth: []
      parameters:
        - in: path
          name: reviewId
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Detailed review information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Review'
        '404':
          description: Review not found
        '401':
          description: Unauthorized - Invalid API Key
        '500':
          description: Internal Server Error
    put:
      summary: Update details of an existing review
      operationId: updateReview
      security:
        - ApiKeyAuth: []
      parameters:
        - in: path
          name: reviewId
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Review'
      responses:
        '200':
          description: Review updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Review'
        '400':
          description: Bad Request - Invalid Data Provided
        '404':
          description: Review not found
        '401':
          description: Unauthorized - Invalid API Key
        '500':
          description: Internal Server Error
    delete:
      summary: Remove an existing review
      operationId: deleteReview
      security:
        - ApiKeyAuth: []
      parameters:
        - in: path
          name: reviewId
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Review deleted successfully
        '404':
          description: Review not found
        '401':
          description: Unauthorized - Invalid API Key
        '500':
          description: Internal Server Error

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-KEY

  schemas:
    Movie:
      type: object
      properties:
        id:
          type: integer
          example: 1
        title:
          type: string
          example: "Inception"
        description:
          type: string
          example: "A mind-bending thriller."
        releaseYear:
          type: integer
          example: 2010
      required:
        - title
        - releaseYear

    Review:
      type: object
      properties:
        id:
          type: integer
          example: 1
        movieId:
          type: integer
          example: 1
        rating:
          type: integer
          minimum: 1
          maximum: 10
          example: 8
        comment:
          type: string
          example: "Great movie with stunning visuals."
      required:
        - movieId
        - rating
